estado(acre).
estado(alagoas).
estado(amapa).
estado(amazonas).
estado(bahia).
estado(ceara).
estado(distrito_federal).
estado(espirito_santo).
estado(goias).
estado(maranhao).
estado(mato_grosso).
estado(mato_grosso_do_sul).
estado(minas_gerais).
estado(para).
estado(paraiba).
estado(parana).
estado(pernambuco).
estado(piaui).
estado(rio_de_janeiro).
estado(rio_grande_do_norte).
estado(rio_grande_do_sul).
estado(rondonia).
estado(roraima).
estado(santa_catarina).
estado(sao_paulo).
estado(sergipe).
estado(tocantins).
capital(maceio).
capital(macapa).
capital(manaus).
capital(salvador).
capital(fortaleza).
capital(brasilia).
capital(vitoria).
capital(goiania).
capital(sao_luis).
capital(cuiaba).
capital(campo_grande).
capital(belo_horizonte).
capital(rio_branco).
capital(belem).
capital(joao_pessoa).
capital(curitiba).
capital(recife).
capital(teresina).
capital(rio_de_janeiro).
capital(natal).
capital(porto_alegre).
capital(porto_velho).
capital(boa_vista).
capital(florianopolis).
capital(sao_paulo).
capital(aracaju).
capital(palmas).
capitalDe(rio_branco,acre).
capitalDe(maceio,alagoas).
capitalDe(macapa,amapa).
capitalDe(manaus,amazonas).
capitalDe(salvador,bahia).
capitalDe(fortaleza,ceara).
capitalDe(brasilia,distrito_federal).
capitalDe(vitoria,espirito_santo).
capitalDe(goiania,goias).
capitalDe(sao_luis,maranhao).
capitalDe(cuiaba,mato_grosso).
capitalDe(campo_grande,mato_grosso_do_sul).
capitalDe(belo_horizonte,minas_gerais).
capitalDe(belem,para).
capitalDe(joao_pessoa,paraiba).
capitalDe(curitiba,parana).
capitalDe(recife,pernambuco).
capitalDe(teresina,piaui).
capitalDe(rio_de_janeiro,rio_de_janeiro).
capitalDe(natal,rio_grande_do_norte).
capitalDe(porto_alegre,rio_grande_do_sul).
capitalDe(porto_velho,rondonia).
capitalDe(boa_vista,roraima).
capitalDe(florianopolis,santa_catarina).
capitalDe(sao_paulo,sao_paulo).
capitalDe(aracaju,sergipe).
capitalDe(palmas,tocantins).